version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "ci:"
      include: "scope"
    
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to Python packages every week
      interval: "weekly"
    commit-message:
      prefix: "deps:"
      include: "scope"
