---
name: 'Yamllint'
description: 'A linter for YAML files.'
inputs:
  python-version:
    description: 'Python version to be used'
    required: true
    default: '3.13.0'
runs:
  using: "composite"
  steps:
    # v4.2.2
    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
    - name: Get changed files
      id: changed-files
      # v45.0.4
      uses: tj-actions/changed-files@dbf178ceecb9304128c8e0648591d71208c6e2c9
      with:
        # Avoid using single or double quotes for multiline patterns
        files: |
          **.yaml
          **.yml
    - name: List all changed files
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: |
          ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
    - name: Set up Python ${{ inputs.python-version }}
      if: steps.changed-files.outputs.any_changed == 'true'
      # v5.3.0
      uses: actions/setup-python@55aad42e4674b58b2b2fb7d8e7552402d922b4e7
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --user yamllint
    - name: Analysing the code with pylint
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: |
          ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: |
        yamllint ${ALL_CHANGED_FILES}
