---
name: Yamllint

"on":
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Get changed-files
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      # v4.2.2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.yaml
            **.yml
      - name: List all changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: |
            ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
    outputs:
      are_files_changed: ${{ steps.changed-files.outputs.any_changed }}
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
  yamllint:
    needs: [changed_files]
    if: needs.changed_files.outputs.are_files_changed == 'true'
    runs-on: ubuntu-latest
    env:
      python-version: 3.13.0
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      # v4.2.2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@55aad42e4674b58b2b2fb7d8e7552402d922b4e7
        # v5.3.0
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user yamllint
      - name: Analysing the code with pylint
        run: |
          yamllint ${{ needs.changed_files.outputs.changed_files }}
